<!DOCTYPE html>
<html>
<head>
    <title><?php echo $this->title; ?> :: [Bind9 Frontend]</title>
    <!-- Bootstrap -->
    <link href="bootstrap/css/bootstrap.css" rel="stylesheet" media="screen">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>
<body>
<div class="container-fluid">
    <div class="row-fluid">
        <div class="span12">
            <?php echo $this->body; ?>
        </div>
    </div>
</div>

<script src="http://code.jquery.com/jquery-latest.js"></script>
<script src="js/jquery.hotkeys.js"></script>
<script src="bootstrap/js/bootstrap-tooltip.js"></script>
<script src="bootstrap/js/bootstrap-modal.js"></script>

<script src="js/bind-frontend-ui.js"></script>
</body>
</html>