<?php
/* @var \Bind\ZoneFile\Standard $records */
$records = $this->records;
?>
            <h1>DNS zone example.com</h1>
            <h3>SOA record and global TTL</h3>
<pre>
$TTL    <?php echo htmlspecialchars($records->getTtl()->getValue()); ?>
@       IN      SOA     <?php echo htmlspecialchars($records->getSoa()->getZone()); ?> <?php echo htmlspecialchars($records->getSoa()->getAdmin()); ?> (
                        <?php echo htmlspecialchars($records->getSoa()->getSerial()); ?>	; serial as date + serial number
                        <?php echo htmlspecialchars($records->getSoa()->getRefresh()); ?>		; refresh in seconds
                        <?php echo htmlspecialchars($records->getSoa()->getRetry()); ?>		; retry in seconds
                        <?php echo htmlspecialchars($records->getSoa()->getExpiry()); ?>		; expire in seconds
                        <?php echo htmlspecialchars($records->getSoa()->getMinTtl()); ?> )		; minimum in seconds
</pre>
            <a class="btn btn-small"><i class="icon-edit"></i> Edit</a>

            <h3>Existed records <a class="btn btn-mini btn-success" id="create-new-record"><i class="icon-plus-sign icon-white"></i> Create new</a></h3>
            <table class="table table-striped table-hover">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Domain</th>
                    <th>Type</th>
                    <th>Raw Value</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
<?php
                    $i = 1;
                    foreach ($records->getRecords() as $record) { ?>
                <tr>
                    <td><?php echo $i++; ?></td>
                    <td><?php echo htmlspecialchars($record->getDomain()); ?></td>
                    <td><?php echo htmlspecialchars($record->getClass()); ?></td>
                    <td><?php echo str_replace(array("\t", "\r", "\n"), array("    ", ' ', ' '), htmlspecialchars($record->getRdata())); ?></td>
                    <td>
                        <a class="btn btn-mini form-edit-button"><i class="icon-edit"></i> Edit</a>
                        <a class="btn btn-mini form-remove-button"><i class="icon-remove-circle"></i> Remove</a>
                    </td>
                </tr>
<?php } ?>

                <tr id="record-add-template" style="display: none;">
                    <td></td>
                    <td><input type="text"  class="form-domain-input" name="record[domain]" placeholder="@, relative or absolute.com."></td>
                    <td><select name="record[5][type]" class="input-small">
                        <option value="A">A</option>
                        <option value="AAAA">AAAA</option>
                        <option value="CNAME">CNAME</option>
                        <option value="NS">NS</option>
                        <option value="MX">MX</option>
                        <option value="TXT">TXT</option>
                        <option value="SRV">SRV</option>
                    </select></td>
                    <td><div class="input-append">
                        <input type="text" name="record[value]" class="input-xxlarge form-value-input" placeholder="1.1.1.1, example.com. or 10 mx.example.com.">
                        <button class="btn" type="button"><i class="icon-question-sign"></i></button>
                    </div></td>
                    <td>
                        <button class="btn btn-mini btn-primary form-save-button"><i class="icon-ok-circle icon-white"></i> Save</button>
                        or <button class="btn btn-mini form-cancel-button">Cancel</button>
                    </td>
                </tr>
                </tbody>
            </table>

            <div id="modal-removal" class="modal hide" role="dialog" tabindex="-1">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h3>Record removal</h3>
                </div>
                <div class="modal-body">
                    <p class="alert alert-error">Are you sure to remove record #<span class="removal-record-id">0</span>?</p>
                    <pre class="removal-record-contents"></pre>
                </div>
                <div class="modal-footer">
                    <button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
                    <button class="btn btn-danger removal-record-do" data-dismiss="modal">Yes, remove it!</button>
                </div>
            </div>